spring.application.name=Borrowly

server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/borrowly
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration - Use environment variables in production
application.security.jwt.secret-key=${JWT_SECRET_KEY:mynameisrutaganirayanisntwaliwhostudiesatrcaandisinlevel4}
application.security.jwt.access-token-expiration=3600000
application.security.jwt.refresh-token-expiration=604800000

spring.jackson.mapper.accept-case-insensitive-enums=true
